name: Nekoray build matrix - cmake

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true # Ensure submodules are checked out
        
      - name: Verify Git integrity
        run: git fsck

      - name: Clear Cache
        run: |
          git clean -fdx
          git reset --hard

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: |
          ./libs/get_source.sh
          GOOS=windows GOARCH=amd64 ./libs/build_go.sh

      - name: Build public resources
        run: ./libs/build_public_res.sh
