name: Nekoray Build for Windows with Xray-core v25.3.6

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release Tag (e.g., v3.26-xray-25.3.6)"
        required: true

jobs:
  build-go:
    runs-on: ubuntu-latest  # Using Ubuntu for Go cross-compilation to Windows
    steps:
      - name: Checking out sources
        uses: actions/checkout@v4  # Updated to v4

      - name: Install Golang
        uses: actions/setup-go@v5  # Updated to v5
        with:
          go-version: ^1.24  # Required for Xray-core v25.3.6

      - name: Download Xray-core v25.3.6
        shell: bash
        run: |
          mkdir -p ../Xray-core
          curl -L https://github.com/XTLS/Xray-core/archive/refs/tags/v25.3.6.tar.gz | tar xz -C ../Xray-core --strip-components=1
          echo "Xray-core v25.3.6 downloaded to ../Xray-core"

      - name: Ensure Scripts Are Executable
        shell: bash
        run: |
          chmod +x ./libs/get_source.sh || echo "get_source.sh not found"
          chmod +x ./libs/build_go.sh || echo "build_go.sh not found"

      - name: Build Xray-core and Nekoray Go Parts
        shell: bash
        env:
          GOOS: windows
          GOARCH: amd64
        run: |
          cd ../Xray-core
          CGO_ENABLED=0 go build -o xray.exe -trimpath -ldflags "-s -w -buildid=" ./main
          cd ../nekoray
          ./libs/get_source.sh  # Fetch additional sources if needed
          GOOS=windows GOARCH=amd64 ./libs/build_go.sh
          mkdir -p deployment/windows_amd64
          mv ../Xray-core/xray.exe deployment/windows_amd64/xray.exe

      - name: Tar Files
        shell: bash
        run: tar czvf artifacts.tgz ./deployment

      - name: Uploading Artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: NekoRay-${{ github.sha }}-Go-Windows-amd64
          path: artifacts.tgz

  build-cpp:
    runs-on: windows-2022
    steps:
      - name: Checking out sources
        uses: actions/checkout@v4  # Updated to v4
        with:
          submodules: recursive

      - name: Install MSVC compiler
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.2  # VS 2019/2022 compatible
          arch: x64

      - name: Download Custom Qt 6.5 SDK
        shell: bash
        env:
          DL_QT_VER: "6.5"
        run: |
          bash ./libs/download_qtsdk_win.sh
          echo "Qt 6.5 downloaded to $PWD/qtsdk/Qt"

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v4  # Updated to v4

      - name: Ensure Scripts Are Executable
        shell: bash
        run: |
          chmod +x ./libs/build_deps_all.sh || echo "build_deps_all.sh not found"
          chmod +x ./libs/env_qtsdk.sh || echo "env_qtsdk.sh not found"
          chmod +x ./libs/deploy_windows64.sh || echo "deploy_windows64.sh not found"

      - name: Build Dependencies
        shell: bash
        run: ./libs/build_deps_all.sh

      - name: Generate Makefile and Build
        shell: bash
        env:
          CC: cl.exe
          CXX: cl.exe
        run: |
          source libs/env_qtsdk.sh $PWD/qtsdk/Qt
          mkdir build
          cd build
          cmake -GNinja -DQT_VERSION_MAJOR=6 -DCMAKE_BUILD_TYPE=Release ..
          ninja -j2
          cd ..
          ./libs/deploy_windows64.sh

      - name: Tar Files
        shell: bash
        run: tar czvf artifacts.tgz ./deployment

      - name: Uploading Artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: NekoRay-${{ github.sha }}-Windows-2022-x64-Qt6.5
          path: artifacts.tgz

  publish:
    runs-on: ubuntu-latest
    needs:
      - build-go
      - build-cpp
    steps:
      - name: Checking out sources
        uses: actions/checkout@v4  # Updated to v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4  # Updated to v4
        with:
          path: download-artifact

      - name: Ensure Deploy Script is Executable
        shell: bash
        run: chmod +x ./libs/env_deploy.sh || echo "env_deploy.sh not found"

      - name: Pack for Windows
        shell: bash
        run: |
          source libs/env_deploy.sh
          find download-artifact -name "*.tgz" | xargs -n1 tar xvzf -C deployment
          cd deployment
          mv windows_amd64 nekoray  # Combine Go and CPP outputs
          zip -r ${{ github.event.inputs.tag }}-standalone-windows64.zip nekoray

      - name: Upload Final Artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: Nekoray-${{ github.event.inputs.tag }}-Windows
          path: deployment/${{ github.event.inputs.tag }}-standalone-windows64.zip
