build-cpp:
  strategy:
    matrix:
      include:
        - platform: windows-2022
          arch: x64
          qt_version: "6.5"
    fail-fast: false
  runs-on: ${{ matrix.platform }}
  steps:
    - name: Checking out sources
      uses: actions/checkout@v3
      with:
        repository: MatsuriDayo/nekoray
        ref: main
        submodules: recursive
    - name: Modify File
      shell: pwsh
      run: |
        if (Test-Path "main\NekoGui_DataStore.hpp") { $content = Get-Content "main\NekoGui_DataStore.hpp" -Raw; if ($content -match "bool remember_enable = false;") { $content = $content -replace "bool remember_enable = false;", "bool remember_enable = true;"; $content | Set-Content "main\NekoGui_DataStore.hpp" -Force } }
        # ... rest of your PowerShell script ...
    - name: Install MSVC compiler
      if: matrix.platform == 'windows-2022'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}
    - name: Windows - Download Custom Qt ${{ matrix.qt_version }} SDK
      shell: bash
      env:
        DL_QT_VER: ${{ matrix.qt_version }}
      run: |
        echo "Downloading Qt SDK for version ${DL_QT_VER}"
        bash ./libs/download_qtsdk_win.sh || echo "Download failed"
    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@master
    - name: Windows - Generate MakeFile and Build
      shell: bash
      env:
        DL_QT_VER: ${{ matrix.qt_version }}
        CC: cl.exe
        CXX: cl.exe
      run: |
        . ./libs/env_qtsdk.sh "$PWD/qtsdk/Qt" || echo "env_qtsdk.sh failed"
        mkdir build || echo "mkdir failed"
        cd build || echo "cd failed"
        cmake -GNinja -DQT_VERSION_MAJOR=6 -DCMAKE_BUILD_TYPE=Release .. --verbose || echo "CMake failed"
        ninja -j2 -v || echo "Ninja failed"
        cd .. || echo "cd .. failed"
        ./libs/deploy_windows64.sh || echo "Deploy failed"
    - name: Tar files
      shell: bash
      run: tar czvf artifacts.tgz ./deployment || echo "Tar failed"
    - name: Uploading Artifact
      uses: actions/upload-artifact@v3
      with:
        name: NekoRay-${{ github.sha }}-${{ matrix.platform }}-${{ matrix.arch }}-Qt${{ matrix.qt_version }}
        path: artifacts.tgz
